# Generated by Django 4.2.6 on 2023-10-31 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transactiontype_transactions_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemindersInterval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='reminder',
            name='Interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.remindersinterval'),
        ),
    ]
