# Generated by Django 4.2.6 on 2023-10-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remindersinterval_alter_reminder_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindersinterval',
            name='Interval',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
